### ISSUE TITLE
DELETE nodes/{id} should only allow ids not names

### ISSUE THREAD

**Issue by tecoholic** [GluuFederation/gluu-flask#31]
The current documentation at http://www.gluu.org/docs-cluster/reference/api/node/ shows that `DELETE` request for nodes using both names and ids are allowed.
* Is this technically possible?
* Can a node deletion can be initiated even before deployment is over?
* Since, we get the ids only when the deployment is over, I feel the API should only allow DELETE requests for ids and not names.
* If deletion can be initiated even before deployment is over. I kindly request documentation to be added for the same.

**Comment by iromli** [comment]
> Since, we get the ids only when the deployment is over, I feel the API should only allow DELETE requests for ids and not names.

That's not true actually. The ID will be populated if a container for the node is created even if the deployment is still on progress. We need the deletion feature to allow node's ID or name because a node with `FAILED` state may not have the ID (for example, there's an error before container is created). On the other hands, node's name is guaranteed to always available regardless of its node's state.

What we can do is to reject deletion if node's state is `IN_PROGRESS`.

**Comment by shouro** [comment]
Right.

**Comment by iromli** [comment]
merged to master in https://github.com/GluuFederation/gluu-flask/commit/2ef612458c39834f519eeea53494e9090d9aeec7
